"use client";
import {useEffect,useState,useRef} from "react";
import Image from "next/image";

import ContactForm from "./_components/ContactForm";
import SolarExchangeLight from "./_components/SolarExchangeLight";
import {Symbol} from "./_components/Shell";
function Photo({name="solar-grid-market.png",alt,priority=false}:{name?:string;alt:string;priority?:boolean}){return <Image src={`/demo-4/${name}`} alt={alt} fill priority={priority} sizes="(max-width:700px) 100vw, 60vw" className="photo"/>}
function Wind(){return <svg className="wind-art" viewBox="0 0 260 160" fill="none" stroke="currentColor" strokeWidth="1" aria-hidden="true">{[0,90,170].map((x,i)=><g key={x} transform={`translate(${x} ${i===1?0:40}) scale(${i===1?1:.7})`}><path d="M45 65 38 155h14L47 65M45 63 43 3q7-3 6 13l-2 47M45 63 4 91q-6-4 6-12l35-16M45 63l48 25q0 7-13-1L45 63"/><circle cx="45" cy="63" r="3"/></g>)}<path d="M0 158c50-25 90-18 130-10s90-18 130 8"/></svg>}
const products=[{title:"اینورتر تک‌فاز",spec:"۲ تا ۶ کیلووات",text:"تبدیل هوشمند انرژی برای سیستم‌های خورشیدی خانگی."},{title:"پنل‌های خورشیدی",spec:"فناوری فتوولتائیک",text:"آغاز یک مسیر پاک؛ پنل‌های متناسب با نیاز و شرایط هر پروژه."},{title:"اینورتر سه‌فاز صنعتی",spec:"۳۰ تا ۸۰ کیلووات",text:"راهکاری برای مدیریت انرژی در نیروگاه‌ها و پروژه‌های بزرگ‌تر."},{title:"اینورتر سه‌فاز تجاری",spec:"۵ تا ۲۵ کیلووات",text:"انتخابی برای کسب‌وکارهایی که به توسعه پایدار فکر می‌کنند."}];
const projects=[{title:"نیروگاه خورشیدی بختران",place:"کرمان · تولید در مقیاس صنعتی",image:"energy-trading-room.png"},{title:"پروژه توسعه انرژی پاک",place:"یزد · بهره‌برداری هوشمند",image:"solar-grid-market.png"},{title:"همراهی از طراحی تا اجرا",place:"اصفهان · توسعه ظرفیت",image:"energy-trading-room.png"}];
export default function DemoFour(){const [slide,setSlide]=useState(0);const [product,setProduct]=useState(1);const [project,setProject]=useState(0);const [solution,setSolution]=useState(0);
const productList=useRef<HTMLDivElement>(null);
const gallery=useRef<HTMLDivElement>(null);
const [previewTop,setPreviewTop]=useState(130);
useEffect(()=>{const list=productList.current;if(!list)return;const update=()=>{const row=list.querySelector<HTMLElement>(".product-row.active");if(row)setPreviewTop(row.offsetTop+row.offsetHeight/2);};update();const observer=new ResizeObserver(update);observer.observe(list);return()=>observer.disconnect();},[product]);
function moveProject(delta:number){const next=(project+delta+projects.length)%projects.length;const track=gallery.current;const card=track?.children[next] as HTMLElement|undefined;if(track&&card){const gap=parseFloat(getComputedStyle(track).columnGap)||0;track.scrollTo({left:-next*(card.offsetWidth+gap),behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});}setProject(next);}
const solutions=[{name:"خورشیدی تجاری",icon:"panel" as const,desc:"انرژی هوشمند برای کسب‌وکار شما",detail:"بررسی الگوی مصرف و فضای قابل استفاده، برای طراحی سیستمی متناسب با نیاز کسب‌وکار."},{name:"طراحی و نصب",icon:"screen" as const,desc:"از نخستین طرح تا راه‌اندازی",detail:"انتخاب تجهیزات، مهندسی و اجرای هماهنگ؛ با نگاهی دقیق به تمام مراحل پروژه."},{name:"نگهداری و پایش",icon:"gear" as const,desc:"برای عملکردی ماندگار",detail:"بازدید دوره‌ای و پایش تولید، برای شناسایی زودهنگام مشکلات و برنامه‌ریزی نگهداری."}];
return <div className="nova">
<main><section className="hero" id="home"><div className="hero-image"><Photo name={slide===0?"energy-trading-room.png":"solar-grid-market.png"} alt="پنل‌های خورشیدی و تیم اجرای نیروگاه" priority/><div className="hero-shade"/><div className="hero-copy"><span>انرژی پاک، برای آینده‌ای ماندگار</span><h1>{slide===0?<>با نیروی خورشید،<br/>آینده را سبز می‌سازیم.</>:<>از تابش امروز،<br/>تا روشنایی فردا.</>}</h1><p>برق تولیدی نیروگاه‌های تابش، پس از تزریق به شبکه سراسری، برای فروش در بورس انرژی عرضه می‌شود.</p><a href="#products" className="button">کشف محصولات ما <i><Symbol name="arrow"/></i></a></div></div><div className="hero-notch"><div className="slider-controls"><button aria-label="اسلاید قبلی" onClick={()=>setSlide(1-slide)}><Symbol name="right"/></button><button className="filled" aria-label="اسلاید بعدی" onClick={()=>setSlide(1-slide)}><Symbol name="left"/></button></div><div className="hero-stat"><strong>{slide===0?"۲۱۰":"۶"}</strong><span>{slide===0?"مگاوات ظرفیت نصب‌شده":"نیروگاه خورشیدی"}<small>آمار نمایشی</small></span></div></div></section>
<section className="about section cream" id="about"><div className="content"><div className="section-intro"><h2>درباره تابش<br/>انرژی گستر</h2><p>ما به آینده‌ای باور داریم که انرژی آن از خورشید می‌آید. از طراحی و ساخت تا بهره‌برداری نیروگاه‌های خورشیدی، برق پاک تولید می‌کنیم. برق تولیدی این مزارع پس از تزریق به شبکه سراسری، مستقیماً در بورس انرژی برای فروش عرضه می‌شود.</p></div><div className="about-grid"><div className="about-photo"><Photo name="energy-trading-room.png" alt="همکاری تیم مهندسی در نصب پنل‌ها"/></div><article className="mission"><span className="icon-circle"><Symbol name="target"/></span><h3>ماموریت ما</h3><p>توسعه راهکارهای مطمئن انرژی خورشیدی و تبدیل ظرفیت طبیعت به نیرویی ماندگار برای خانه‌ها، کسب‌وکارها و صنایع.</p></article><svg className="scribble" viewBox="0 0 180 130" fill="none" aria-hidden="true"><path d="M12 24C52 2 110 17 113 53C117 94 59 86 75 56C90 26 152 54 155 109M144 101L155 109L161 96" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/></svg><article className="vision"><span className="icon-circle"><Symbol name="eye"/></span><h3>چشم‌انداز ما</h3><p>ساختن آینده‌ای که در آن انرژی پاک در دسترس‌تر باشد؛ با نوآوری مسئولانه، مهندسی دقیق و احترام به زمین.</p></article><Wind/></div></div></section>
<section className="exchange-section content"><div className="exchange-copy"><span className="icon-circle"><Symbol name="screen"/></span><div><span className="section-kicker">از مزرعه خورشیدی تا بازار انرژی</span><h2>برق پاک تولید می‌کنیم،<br/>در بورس انرژی عرضه می‌کنیم.</h2></div></div><SolarExchangeLight/></section><section className="products section" id="products"><h2>محصولات ما</h2><div className="product-list" ref={productList}>{products.map((p,i)=><button key={p.title} className={product===i?"product-row active":"product-row"} onClick={()=>setProduct(i)} aria-expanded={product===i}><span className="row-inner"><small>{["۰۱","۰۲","۰۳","۰۴"][i]}.</small><span className="row-title">{p.title}<em>{p.spec}</em>{product===i&&<span className="product-description">{p.text}</span>}</span><Symbol name="arrow"/></span></button>)}<div className="product-preview" style={{top:previewTop}} aria-hidden="true"><Photo alt="" name={product===1?"solar-grid-market.png":"energy-trading-room.png"}/><span>{products[product].title}</span></div></div></section>
<section className="innovation section cream" id="process"><div className="content"><div className="innovation-top"><div className="innovation-photo"><Photo name="energy-trading-room.png" alt="طراحی و اجرای تجهیزات خورشیدی"/></div><div><h2>نوآوری،<br/>در تمام مسیر اجرا.</h2><h4>مهندسی دقیق و کنترل کیفیت</h4><p>از شناخت نیاز تا انتخاب تجهیزات، هر تصمیم بر پایه شرایط پروژه گرفته می‌شود. فرآیند ما برای رسیدن به عملکردی مطمئن، قابل پایش و پایدار طراحی شده است.</p><div className="quality"><div><span className="icon-circle"><Symbol name="target"/></span><b>کیفیت در اجرا</b><small>دقت در هر مرحله</small></div><div><span className="icon-circle"><Symbol name="leaf"/></span><b>همراه با طبیعت</b><small>نگاهی مسئولانه به منابع</small></div></div></div></div><div className="steps">{[["شناخت و طراحی","بررسی محل، میزان تابش و نیاز مصرف؛ برای طراحی راهکاری متناسب با شما."],["مهندسی و تأمین تجهیزات","انتخاب تجهیزات و برنامه‌ریزی اجرای پروژه بر اساس مشخصات فنی."],["نصب و راه‌اندازی","اجرای هماهنگ، آزمون تجهیزات و آماده‌سازی سیستم برای تولید انرژی."],["پایش و نگهداری","بررسی عملکرد و نگهداری برنامه‌ریزی‌شده برای ادامه تولید پایدار."]].map(([t,d],i)=><article key={t}><span>{["۰۱","۰۲","۰۳","۰۴"][i]}.</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div><Wind/></div></section>
<section className="projects section" id="projects"><div className="content"><div className="projects-heading"><h2>پروژه‌های ما</h2><div className="slider-controls"><button aria-label="پروژه قبلی" onClick={()=>moveProject(-1)}><Symbol name="right"/></button><button aria-label="پروژه بعدی" onClick={()=>moveProject(1)}><Symbol name="left"/></button></div></div><div className="project-gallery" ref={gallery} onScroll={()=>{const track=gallery.current;if(!track)return;const bounds=track.getBoundingClientRect();let best=0,distance=Infinity;Array.from(track.children).forEach((card,i)=>{const d=Math.abs(card.getBoundingClientRect().right-bounds.right);if(d<distance){distance=d;best=i;}});setProject(best);}}>{projects.map(p=><article key={p.title}><div className="project-photo"><Photo name={p.image} alt={p.title}/><span className="project-seal"><Symbol name="leaf"/></span></div><h3>{p.title}</h3><p>{p.place}</p></article>)}</div><small className="project-note">پروژه‌ها برای نمایش طراحی ارائه شده‌اند.</small></div></section>
<section className="solutions" aria-label="راهکارهای ما"><div className="solution-grid"><h2>راهکارهای<br/>ما</h2>{solutions.map((s,i)=><button key={s.name} className={solution===i?"solution active":"solution"} onClick={()=>setSolution(i)} aria-pressed={solution===i}><span className="icon-circle"><Symbol name={s.icon}/></span><h3>{s.name}</h3><p>{s.desc}</p></button>)}</div><p className="solution-detail" aria-live="polite">{solutions[solution].detail}</p></section>
<section className="contact section" id="contact"><div className="contact-heading"><h2>با هم، یک آینده روشن بسازیم.</h2><p>برای پروژه بعدی یا یک پرسش ساده، گفت‌وگو را از اینجا شروع کنید.</p></div><ContactForm/><Wind/></section>
<section className="location" aria-label="ارتباط با تیم تابش"><svg className="map-lines" viewBox="0 0 1200 250" preserveAspectRatio="none" aria-hidden="true"><rect width="1200" height="250" fill="#e8eee3"/><path d="M0 140 1200 80M0 70l1200 70M150 0l60 250M480 0l-50 250M850 0l80 250M1050 0l-60 250" stroke="#fff" strokeWidth="18" fill="none"/><path d="M550 0q-80 80 0 140t-60 110" stroke="#b4d6db" strokeWidth="45" fill="none"/><path d="m0 230 1200-190M300 0l80 250M700 0l70 250" stroke="#cbd3c5" strokeWidth="4" fill="none"/></svg><div><span className="icon-circle"><Symbol name="pin"/></span><h3>یک گفت‌وگو تا شروع همکاری</h3><p>شنبه تا چهارشنبه · ۸ تا ۱۶</p><a href="#contact">ارتباط با تیم تابش ↗</a></div><small>تصویر شماتیک؛ موقعیت واقعی نیست</small></section></main>
</div>;
}
