"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type SymbolName="panel"|"target"|"eye"|"leaf"|"gear"|"screen"|"arrow"|"left"|"right"|"menu"|"close"|"pin";
export function Symbol({name="panel"}:{name?:SymbolName}){const paths:Record<SymbolName,React.ReactNode>={panel:<><path d="M5 4h14l3 13H2L5 4Zm-1 6h16M9 4 8 17m7-13 1 13M12 17v4m-4 0h8"/></>,target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="m12 12 8-9m-1 0h3v3"/></>,eye:<><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>,leaf:<><path d="M21 3C9 1 1 9 5 16s17 4 16-13ZM3 22l13-13M9 16l-1-5m6 0h5"/></>,gear:<><path d="m9 3 1-2h4l1 2 3 2 3 1-1 4v4l1 4-3 1-3 2-1 2h-4l-1-2-3-2-3-1 1-4v-4L3 6l3-1 3-2Z"/><circle cx="12" cy="12" r="4"/></>,screen:<><rect x="2" y="3" width="20" height="14" rx="1"/><path d="M12 17v4m-4 0h8M8 9l3 3 5-6"/></>,arrow:<path d="M18 18 6 6m0 10V6h10"/>,left:<path d="m14 5-7 7 7 7"/>,right:<path d="m10 5 7 7-7 7"/>,menu:<path d="M4 6h16M4 12h16M4 18h16"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,pin:<><path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></>};return <svg className="symbol" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>}
export function Brand(){return <a className="brand" href="/demo-4"><span><Symbol/></span><b>تابش<small>Tabesh Energy</small></b></a>}

export function Header(){const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);
useEffect(()=>{const update=()=>setScrolled(window.scrollY>25);update();window.addEventListener("scroll",update,{passive:true});return()=>window.removeEventListener("scroll",update);},[]);
return <header className={scrolled?"site-header raised":"site-header"}><div className="header-inner"><Brand/><button className="menu-toggle" aria-expanded={menu} aria-controls="nova-menu" aria-label={menu?"بستن منو":"بازکردن منو"} onClick={()=>setMenu(!menu)}><Symbol name={menu?"close":"menu"}/></button><nav id="nova-menu" className={menu?"open":""}>{[["اصلی",""],["درباره ما","about"],["اخبار / رویدادها","news"],["بلاگ","blog"],["تماس با ما","contact"]].map(([t,id])=><Link key={id} href={`/demo-4${id ? `/${id}` : ""}`} onClick={()=>setMenu(false)}>{t}</Link>)}</nav><a href="/demo-4/contact" className="button header-cta">درخواست مشاوره</a></div></header>;}
export function Footer(){return <footer><div className="content footer-grid"><div><Brand/><p>فناوری هوشمند و انرژی پاک؛<br/>برای آینده‌ای روشن‌تر و زمینی سبزتر.</p><Link href="/">مشاهده همه دموها ↗</Link></div><div><h4>دسترسی سریع</h4><Link href="/demo-4">اصلی</Link><Link href="/demo-4/about">درباره ما</Link><Link href="/demo-4/news">اخبار / رویدادها</Link><Link href="/demo-4/blog">بلاگ</Link><Link href="/demo-4/contact">تماس با ما</Link></div><div><h4>در ارتباط باشیم</h4><p>تیم تابش انرژی گستر<br/>پاسخ‌گوی پرسش‌ها و پیشنهادهای شما</p><a href="/demo-4/contact">درخواست مشاوره ↗</a></div></div><div className="content copyright"><span>© ۲۰۲۶ تابش انرژی گستر</span><span>دموی طراحی · اطلاعات و آمار نمونه هستند.</span></div></footer>;}
